// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using app2.Data;

namespace app2.Migrations
{
    [DbContext(typeof(MISDbContext))]
    partial class MISDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("app2.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("createdDate");

                    b.Property<string>("productCode");

                    b.Property<string>("productName");

                    b.HasKey("productId");

                    b.ToTable("products");
                });
#pragma warning restore 612, 618
        }
    }
}
